### ISSUE TITLE
java.lang.String.startsWith() 사용에 관하여 (125페이지 예제)

### ISSUE THREAD

**Issue by iamkyu** [slipp/jwp-book#2]
여기에 등록할 내용이 맞는지 모르겠습니다.

``` java
// url = "/user/create?userId=test&password=pass&name=tester&email=a@b.com"
if ("/user/create".startsWith(url)
```

책 125페이지에서, 요청 URL을 분기처리하는 부분에서 위와 같이 startsWith 메서드가 사용되었는데, 비교 하는 스트링이 startsWith()에 매개변수로 넘기는 스트링보다 짧으면 `false` 를 반환하도록 구현되어 있는걸로 확인했습니다.
바쁘신 와중에 오타이신 듯 합니다. 확인하셔서 정오표에 추가해주시면 감사하겠습니다.

**Comment by javajigi** [comment]
앗. 감사합니다.
equals의 경우 NullPointerException 발생을 막기 위해 하드 코딩하는 문자열을 앞에 두다 보니 위와 같이 실수로 수정을 해버렸네요.

혹시 이 이슈를 보시는 분들을 위해 정정한 코드를 남기면 다음과 같아요.
// url = "/user/create?userId=test&password=pass&name=tester&email=a@b.com"
if (url.startsWith("/user/create"))
